# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 569)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ScanFileLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.ScanFileLabel.setObjectName("ScanFileLabel")
        self.horizontalLayout.addWidget(self.ScanFileLabel)
        self.ScanFileName = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ScanFileName.setObjectName("ScanFileName")
        self.horizontalLayout.addWidget(self.ScanFileName)
        self.ScanFileSelectButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.ScanFileSelectButton.setObjectName("ScanFileSelectButton")
        self.horizontalLayout.addWidget(self.ScanFileSelectButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.OneAnswerCheckbox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.OneAnswerCheckbox.setChecked(True)
        self.OneAnswerCheckbox.setObjectName("OneAnswerCheckbox")
        self.verticalLayout.addWidget(self.OneAnswerCheckbox)
        self.AnswerInFileCheckbox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.AnswerInFileCheckbox.setChecked(True)
        self.AnswerInFileCheckbox.setObjectName("AnswerInFileCheckbox")
        self.verticalLayout.addWidget(self.AnswerInFileCheckbox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AnswerFileLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.AnswerFileLabel.setEnabled(False)
        self.AnswerFileLabel.setObjectName("AnswerFileLabel")
        self.horizontalLayout_2.addWidget(self.AnswerFileLabel)
        self.AnswerFileName = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.AnswerFileName.setEnabled(False)
        self.AnswerFileName.setObjectName("AnswerFileName")
        self.horizontalLayout_2.addWidget(self.AnswerFileName)
        self.AnswerFileSelectButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.AnswerFileSelectButton.setEnabled(False)
        self.AnswerFileSelectButton.setObjectName("AnswerFileSelectButton")
        self.horizontalLayout_2.addWidget(self.AnswerFileSelectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OutputFileLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.OutputFileLabel.setObjectName("OutputFileLabel")
        self.horizontalLayout_3.addWidget(self.OutputFileLabel)
        self.OutputFileName = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.OutputFileName.setObjectName("OutputFileName")
        self.horizontalLayout_3.addWidget(self.OutputFileName)
        self.OutputFileSelectButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.OutputFileSelectButton.setObjectName("OutputFileSelectButton")
        self.horizontalLayout_3.addWidget(self.OutputFileSelectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.ScanButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.ScanButton.setObjectName("ScanButton")
        self.verticalLayout.addWidget(self.ScanButton)
        self.OutputTextArea = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.OutputTextArea.setGeometry(QtCore.QRect(10, 270, 521, 221))
        self.OutputTextArea.setObjectName("OutputTextArea")
        self.ClearOutputButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ClearOutputButton.setGeometry(QtCore.QRect(10, 500, 111, 26))
        self.ClearOutputButton.setObjectName("ClearOutputButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.AnswerInFileCheckbox.clicked['bool'].connect(self.AnswerFileName.setDisabled) # type: ignore
        self.AnswerInFileCheckbox.clicked['bool'].connect(self.AnswerFileSelectButton.setDisabled) # type: ignore
        self.ClearOutputButton.clicked.connect(self.OutputTextArea.clear) # type: ignore
        self.AnswerInFileCheckbox.clicked['bool'].connect(self.AnswerFileLabel.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MCQ Scanning"))
        self.ScanFileLabel.setText(_translate("MainWindow", "Scan file"))
        self.ScanFileSelectButton.setText(_translate("MainWindow", "Select"))
        self.OneAnswerCheckbox.setText(_translate("MainWindow", "Warn if there is more than one answer per question"))
        self.AnswerInFileCheckbox.setText(_translate("MainWindow", "Answers in scan file (matriculation number 00000000)"))
        self.AnswerFileLabel.setText(_translate("MainWindow", "Answer file"))
        self.AnswerFileSelectButton.setText(_translate("MainWindow", "Select"))
        self.OutputFileLabel.setText(_translate("MainWindow", "Output file"))
        self.OutputFileSelectButton.setText(_translate("MainWindow", "Select"))
        self.ScanButton.setText(_translate("MainWindow", "Scan"))
        self.ClearOutputButton.setText(_translate("MainWindow", "Clear output box"))
